import { type NextPage } from "next";
import Head from "next/head";
import Graph from "~/components/Graph";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Automata</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css"
          integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-3 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          <span className="text-[hsl(280,100%,70%)]">Auto</span>mata
        </h1>
        <h2 className="mb-5 text-3xl text-white">Empowering theory.</h2>
        <Graph />
      </main>
    </>
  );
};

export default Home;
